### ISSUE TITLE
on using Set for shuffling 

### ISSUE THREAD

**Issue by hkdtam** [SqrtNegInf/Rosettacode-Raku-Smoke#2]
Hi again :-D

There is nothing wrong with your code, just that it is easier for me to use the Issue interface to track my question(s) (instead of having them buried under "Commit Comments".

In my local experiment earlier, I tried to play with Set to set the initial state, so it was something like

```` (1..99).Set.keys````

and to my surprise, the output isn't deterministic.  So do you have any idea on this ? and what/where is the entropy and if I can control it?  

Thanks in advance.

**Comment by SqrtNegInf** [comment]
The order of 'keys' is always undefined/random, and this is independent of `srand` (which can control what rand, pick, and roll produce).  This is a security feature, so not going to change.  Makes some RC tasks challenging to repeatably test...

**Comment by hkdtam** [comment]
Oh you mean [hash randomization](https://cry.nu/perl6/secure-hashing-for-moarvm/)? that is elementary :D  and I should have known it because I filed an [related issue](https://github.com/sergot/http-useragent/issues/199#issue-326476268) before .. huh my rate of unlearning is spectacular
